#!/usr/bin/env bash

if which doas; then
    su=doas
elif which sudo; then
    su=sudo
else
    echo "[ERROR] Cannot get root access"
    return 1
fi

if [ -f "pkgit" ] && [ -f "bldit-default" ]; then
    "$su" cp pkgit "/usr/bin"
    "$su" cp bldit-default "/var/lib/pkgit/bldit/bldit-default"
else
    curl "https://raw.githubusercontent.com/dacctal/pkgit/refs/heads/main/pkgit" >>pkgit
    chmod +x pkgit
    "$su" mv pkgit /usr/bin

    curl "https://raw.githubusercontent.com/dacctal/pkgit/refs/heads/main/bldit-default" >>bldit-default
    chmod +x bldit-default
    "$su" mkdir -p /etc/pkgit/bldit/
    "$su" mv bldit-default /etc/pkgit/bldit/
fi
